# Generated by Django 5.0.1 on 2025-12-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cost_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voip',
            name='voip_type',
            field=models.CharField(choices=[('teams', 'Microsoft Teams'), ('3cx', '3CX'), ('yeastar', 'Yeastar'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
