# Generated by Django 5.0.1 on 2025-12-02 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_voip_voip_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMMEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Device hostname', max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('server', 'Server'), ('workstation', 'Workstation'), ('other', 'Other')], default='other', max_length=50)),
                ('cpu_model', models.CharField(blank=True, max_length=255)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('ram_gb', models.FloatField(default=0, help_text='RAM in GB')),
                ('disk_total_gb', models.FloatField(default=0)),
                ('disk_free_gb', models.FloatField(default=0)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('logged_in_user', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time seen in RMM', null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('raw_rmm_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmm_endpoints', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmm_endpoints', to='core.organization')),
            ],
            options={
                'db_table': 'rmm_endpoints',
                'ordering': ['-last_sync'],
                'indexes': [models.Index(fields=['organization', '-last_sync'], name='rmm_endpoin_organiz_a5c440_idx'), models.Index(fields=['status'], name='rmm_endpoin_status_0d8697_idx')],
            },
        ),
    ]
